/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "inverter.v:1.1-10.10" *)
module inverter(a, y);
  (* src = "inverter.v:3.12-3.13" *)
  input a;
  wire a;
  (* src = "inverter.v:4.13-4.14" *)
  output y;
  wire y;
  assign y = ~a;
endmodule
